[package]
name = "snake-rs"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["wrott <wrottkitkatt@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ncurses = "5.101.0"
rand = "0.8.4"
